server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # \u5F53\u524D\u6570\u636E\u6E90\u64CD\u4F5C\u7C7B\u578B
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql\u9A71\u52A8\u5305
    url: jdbc:mysql://localhost:3306/quickbi?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: pass1234

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.payment8081.entity    # \u6240\u6709Entity\u522B\u540D\u7C7B\u6240\u5728\u5305