server:
  port: 80
spring:
  application:
    name: cloud-provider-hystrix-order80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

# feign hystrix 启用, feign fallback 声明必须启用，不然还是超时，降级熔断， 限流无法生效
feign:
  hystrix:
    enabled: true
